---
types:
  - key: TARIFF
    name: { en: "Tariff",  ru: "Тариф" }
    isApp: true
    isAbstract: false
    icon: local_atm
    links:
      - key: CONNECT-TO-USER
        builderType: SEARCH
        name: { en: "User", ru: "Пользователь" }
        icon: person
        typeKey: USER
        max: 10
    functions:
      - key: CHANGE-FIELD
        name: { en: "Change price", ru: "Изменить стоимость" }
        actionName: { en: "Change price", ru: "Изменить стоимость" }
        withEntityId: true
        isShowFormWithoutData: false
        showResponse: true
        inputSpec: |
                    {
                        "type": "object",
                        "properties": {
                            "newPrice": {
                                "title": "New price",
                                "type": "string"
                            }
                        }
                    }
      #  inputForm: |
       #            {
        #              "form":[
         #                "userFirstname",
          #               "userLastName"
           #          ]
            #       }

      - key: CONNECT-USER
        name: { en: "Connect user", ru: "Подключить пользователя" }
        actionName: { en: "Connect user", ru: "Подключить пользователя" }
        withEntityId: true
        isShowFormWithoutData: false
        showResponse: true
        inputSpec: |

                {
                  "type": "object",
                  "properties": {
                    "userName": {
                      "title": "User name",
                      "type": "string"
                    }
                  }
                }
        inputForm: |
                {
                    "form":[
                             {
                               "key": "userName",
                               "type": "rest-select",
                               "url": "/entity/api/_search-with-typekey/xm-entities?typeKey=USER&page=0&size=100&sort=name,asc",
                               "labelField": "name",
                               "valueField": "id",
                               "readonly": false,
                               "title": { "en": "Select user", "ru": "Выберите пользователя" },
                               "showDataFields": [{
                                  "title": "First name",
                                  "value": "userFirstname"
                                 },
                                 {
                                  "title": "Last name",
                                  "value": "userLastName"
                                 }
                               ]
                             }
                            ]
                }
    dataSpec: |
      {
          "type": "object",
          "properties": {
              "tariffName": {
                  "title": "Name",
                  "type": "string"
              },
              "tariffPrice": {
                  "title": "Price",
                  "type": "string"
              },
              "tariffFeatures": {
                  "title": "Features",
                  "type": "string"
              }
          },
          "required": [
              "tariffName",
              "tariffPrice"
          ]
      }
    dataForm: |
      {
          "form":[
                     "tariffName",
                     "tariffPrice",
                     "tariffFeatures",
                     {
                       "type": "submit",
                       "style": "btn-info",
                       "title": "Update"
                     }
                 ]
      }