---
types:
  - key: TARIFF
    name: { en: "Tariff",  ru: "Тариф" }
    isApp: true
    isAbstract: false
    icon: local_atm
    states:
      - key: CONNECT
        name: { en: "Connect", ru: "Подключить" }
        icon: link
        color: "#117f0d"
    functions:
      - key: CONNECT-USER
        name: { en: "User connection", ru: "Подключение пользователя" }
        actionName: { en: "Connect user", ru: "Подключить пользователя" }
        allowedStateKeys:
          - CONNECT
        withEntityId: false
        isShowFormWithoutData: false
        inputSpec: |
                    {
                        "type": "object",
                        "properties": {
                            "userFirstname": {
                                "title": "First name",
                                "type": "string"
                            },
                            "userLastName": {
                                "title": "Last Name",
                                "type": "string"
                            }
                        }
                    }
        inputForm: |
                   {
                      "form":[
                         "userFirstname",
                         "userLastName"
                     ]
                   }
    dataSpec: |
      {
          "type": "object",
          "properties": {
              "tariffName": {
                  "title": "Name",
                  "type": "string"
              },
              "tariffPrice": {
                  "title": "Price",
                  "type": "string"
              },
              "tariffFeatures": {
                  "title": "Features",
                  "type": "string"
              }
          },
          "required": [
              "tariffName",
              "tariffPrice"
          ]
      }
    dataForm: |
      {
          "form":[
                     "tariffName",
                     "tariffPrice",
                     "tariffFeatures",
                     {
                       "type": "submit",
                       "style": "btn-info",
                       "title": "Update"
                     }
                 ]
      }