---
types:
  - key: TARIFF
    name: { en: "Tariff",  ru: "Тариф" }
    isApp: true
    isAbstract: false
    icon: local_atm
    states:
      - key: CONNECT
        name: { en: "Connect", ru: "Подключить" }
        icon: link
        color: "#117f0d"
    links:
      - key: CONNECT-USER
        builderType: SEARCH
        name: { en: "User", ru: "Пользователь" }
        icon: person
        typeKey: USER
        max: 10
    functions:
      - key: CHANGE-FIELD
        name: { en: "Change price", ru: "Изменить стоимость" }
        actionName: { en: "Change price", ru: "Изменить стоимость" }
        withEntityId: true
        isShowFormWithoutData: false
        showResponse: true
        inputSpec: |
                    {
                        "type": "object",
                        "properties": {
                            "newPrice": {
                                "title": "New price",
                                "type": "string"
                            }
                        }
                    }
      #  inputForm: |
       #            {
        #              "form":[
         #                "userFirstname",
          #               "userLastName"
           #          ]
            #       }

    dataSpec: |
      {
          "type": "object",
          "properties": {
              "tariffName": {
                  "title": "Name",
                  "type": "string"
              },
              "tariffPrice": {
                  "title": "Price",
                  "type": "string"
              },
              "tariffFeatures": {
                  "title": "Features",
                  "type": "string"
              }
          },
          "required": [
              "tariffName",
              "tariffPrice"
          ]
      }
    dataForm: |
      {
          "form":[
                     "tariffName",
                     "tariffPrice",
                     "tariffFeatures",
                     {
                       "type": "submit",
                       "style": "btn-info",
                       "title": "Update"
                     }
                 ]
      }