---
types:
  - key: TARIFF
    name: { en: "Tariff",  ru: "Тариф" }
    isApp: true
    isAbstract: false
    icon: local_atm
    functions:
      - key: CHANGE-FIELD
        name: { en: "Change price", ru: "Изменить стоимость" }
        actionName: { en: "Change price", ru: "Изменить стоимость" }
        withEntityId: true
        isShowFormWithoutData: false
        showResponse: true
        inputSpec: |
                    {
                        "type": "object",
                        "properties": {
                            "newPrice": {
                                "title": "New price",
                                "type": "string"
                            }
                        }
                    }

      - key: CONNECT-USER
        name: { en: "Connect user", ru: "Подключить пользователя" }
        actionName: { en: "Connect user", ru: "Подключить пользователя" }
        withEntityId: true
        isShowFormWithoutData: false
        showResponse: true
        inputSpec: |

                {
                  "type": "object",
                  "properties": {
                    "userValue": {
                      "title": "User value",
                      "type": ["string", "number"]
                    }
                  }
                }
        inputForm: |
                {
                    "form": [
                             {
                               "key": "userValue",
                               "type": "rest-select",
                               "url": "/entity/api/_search-with-typekey/xm-entities?typeKey=USER&page=0&size=100&sort=id,asc",
                               "labelField": "name",
                               "valueField": "id",
                               "readonly": false,
                               "title": "Please, select user",
                               "placeholder": "Please, select user"
                             }
                            ]
                }
    dataSpec: |
      {
          "type": "object",
          "properties": {
              "tariffName": {
                  "title": "Name",
                  "type": "string"
              },
              "tariffPrice": {
                  "title": "Price",
                  "type": "string"
              },
              "tariffFeatures": {
                  "title": "Features",
                  "type": "string"
              }
          },
          "required": [
              "tariffName",
              "tariffPrice"
          ]
      }
    dataForm: |
      {
          "form":[
                     "tariffName",
                     "tariffPrice",
                     "tariffFeatures",
                     {
                       "type": "submit",
                       "style": "btn-info",
                       "title": "Update"
                     }
                 ]
      }