---
types:
  - key: TARIFF
    name: { en: "Tariff",  ru: "Тариф" }
    isApp: true
    isAbstract: false
    icon: local_atm
    states:
      - key: CONNECT
        name: { en: "Connect", ru: "Подключить" }
        icon: link
        color: "#117f0d"
    dataSpec: |
      {
          "type": "object",
          "properties": {
              "tariffName": {
                  "title": "Name",
                  "type": "string"
              },
              "tariffPrice": {
                  "title": "Price",
                  "type": "string"
              },
              "tariffFeatures": {
                  "title": "Features",
                  "type": "string"
              }
          },
          "required": [
              "tariffName",
              "tariffPrice"
          ]
      }
    dataForm: |
      {
          "form":[
                     "tariffName",
                     "tariffPrice",
                     "tariffFeatures",
                     {
                       "type": "submit",
                       "style": "btn-info",
                       "title": "Save"
                     }
                 ]
      }