---
types:
  - key: USER
    name: { en: "User",  ru: "Пользователь" }
    isApp: true
    isAbstract: false
    states:
      - key: NEW
        name: { en: "New", ru: "Новый" }
        icon: fiber_new
        color: '#FFEB3B'