---
types:
  - key: USER
    name: { en: "User",  ru: "Пользователь" }
    isApp: true
    isAbstract: false
    dataSpec: |
          {
              "type": "object",
              "properties": {
                  "userFirstname": {
                      "title": "First name",
                      "type": "string"
                  },
                  "userLastName": {
                      "title": "Last Name",
                      "type": "string"
                  }
              },
              "required": [
                  "userFirstname",
                  "userLastName"
              ]
          }
    dataForm: |
          {
              "form":[
                         "userFirstname",
                         "userLastName",
                         {
                            "type": "submit",
                            "style": "btn-info",
                            "title": "Update"
                         }
                     ]
          }